### ISSUE TITLE
cePolyfill(window) fails if called twice

### ISSUE THREAD

**Issue by kapouer** [WebReflection/custom-elements#3]
Hi, i'm using version 0.2.15 and esm-style loading
```
import cePolyfill from '@webreflection/custom-elements';
const customElements = cePolyfill(self || window || global);
```

when doing development i called cePolyfill(window) twice (by accident).
I noticed several errors like
```
index.js:23 Uncaught (in promise) TypeError: Failed to delete an indexed property from 'HTMLFormElement': Index property deleter is not supported.
    at expando (index.js:23)
    at Object.handle (index.js:166)
    at loop (index.js:38)
    at parse (index.js:61)
    at index.js:281
```

removing the additional cePolyfill call stopped those from appearing.

I suppose `cePolyfill` should be able to support being called a second time without failing (i.e. be idempotent).

**Comment by WebReflection** [comment]
can't do that, sorry, as features detection is basd on the global, and if you don't save `customElements` to the global, all things will start from scratch again (it's inevitable).

You can import and initialize it from another file, as module, to be sure this won't happen again, or you can set `customElements` to the global yourself, as this library won't do it, because that'd be obtrusive.

**Comment by WebReflection** [comment]
P.S. this is not the right module, you want to use `@ungap/custom-elements` instead, not this one, as that's the official one, even if retrieved by this one, but that can change in the future.

**Comment by WebReflection** [comment]
P.S.2 added a note in the README
https://github.com/WebReflection/custom-elements#warning-ungapcustom-elements-is-what-you-are-looking-for
